# -*- coding: utf-8 -*-
"""requirments_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojmfT_GPpBDvEuGDA9RHUEpeDnotD37j
"""

requests
beautifulsoup4
sentence-transformers
transformers