# -*- coding: utf-8 -*-
"""test _url2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JgcgEaqyP2s6jVsi4fiHBPkCQYPM41HH
"""

from deliverable2 import *
import json
import random

# Instantiate the URLValidator class
validator = URLValidator()

# List of queries and corresponding URLs
queries_urls = [
    ("Latest advancements in AI", "https://example.com/ai-news"),
    ("Climate change effects", "https://example.com/climate-change"),
    ("Stock market trends", "https://example.com/stock-market"),
    ("Healthy diet tips", "https://example.com/healthy-diet"),
    ("Best programming languages", "https://example.com/programming"),
    ("Space exploration updates", "https://example.com/space"),
    ("Cybersecurity threats", "https://example.com/cybersecurity"),
    ("Electric vehicle advancements", "https://example.com/ev"),
    ("Blockchain technology", "https://example.com/blockchain"),
    ("Mental health awareness", "https://example.com/mental-health")
]

# Placeholder function ratings for demonstration
formatted_output = []

for query, url in queries_urls:
    result = validator.rate_url_validity(query, url)
    result["Function Rating"] = random.randint(1, 5)  # Simulated rating
    result["Custom Rating"] = random.randint(1, 5)  # Simulated rating
    formatted_output.append(result)

# Print the formatted output
print(json.dumps(formatted_output, indent=2))